location    = "eastus"
az-tenant-id        = "xx-xx-xx-xx-xx"  # Replace with your Azure Tenant ID
az-subscription-id  = "xx-xx-xx-xx-xx"  # Replace with your Azure Subscription ID
net-vnet-cidr   = "10.10.0.0/16"
net-subnet-cidr = "10.10.1.0/24"
#linux_vm_size        = "Standard_B2s"
linux_vm_size        = "Standard_B1s"  # 1 vCPUs, 1 GB RAM
linux_admin_username = "adminuser"
linux_admin_password = "Password@321"
